name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: prebuild
      run: ci/prebuild.sh
    - name: build
      run: ci/build.sh
